


const logTypes = {
    USER_ACTION: 'USER_ACTION',
    SYSTEM_EVENT: 'SYSTEM_EVENT',
    SECURITY_EVENT: 'SECURITY_EVENT',
    DATA_CHANGE: 'DATA_CHANGE',
    ANOMALY_DETECTION: 'ANOMALY_DETECTION',
    PERFORMANCE_METRIC: 'PERFORMANCE_METRIC',
    ERROR_LOG: 'ERROR_LOG',
    AUDIT_LOG: 'AUDIT_LOG',
    ACCESS_LOG: 'ACCESS_LOG',
    DEBUG_LOG: 'DEBUG_LOG',
    INFO : 'INFO',
    WARNING : 'WARNING',
    CRITICAL : 'CRITICAL',
    REGISTERED_USERS : 'REGISTERED_USERS',
    ACTIVE_USERS : 'ACTIVE_USERS',
    INACTIVE_USERS : 'INACTIVE_USERS',
    FLAGGED_ROWS : 'FLAGGED_ROWS',
    RESOLVED_FLAGS : 'RESOLVED_FLAGS',
}


module.exports = {  
    logTypes
}